/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.bliss.framework.thriftgen.xgame.xgameservice;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum LogoutReason implements org.apache.thrift.TEnum {
  USER_LOGOUT(1),
  SYSTEM_LOGOUT(2);

  private final int value;

  private LogoutReason(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static LogoutReason findByValue(int value) { 
    switch (value) {
      case 1:
        return USER_LOGOUT;
      case 2:
        return SYSTEM_LOGOUT;
      default:
        return null;
    }
  }
}
