/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.bliss.framework.thriftgen.xgame.tcommon;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class TResponseInfo implements org.apache.thrift.TBase<TResponseInfo, TResponseInfo._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TResponseInfo");

  private static final org.apache.thrift.protocol.TField USER_ID_RECEIVE_FIELD_DESC = new org.apache.thrift.protocol.TField("userIdReceive", org.apache.thrift.protocol.TType.LIST, (short)1);
  private static final org.apache.thrift.protocol.TField MESSAGE_DATA_FIELD_DESC = new org.apache.thrift.protocol.TField("messageData", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TResponseInfoStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TResponseInfoTupleSchemeFactory());
  }

  public List<Integer> userIdReceive; // required
  public ByteBuffer messageData; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    USER_ID_RECEIVE((short)1, "userIdReceive"),
    MESSAGE_DATA((short)2, "messageData");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // USER_ID_RECEIVE
          return USER_ID_RECEIVE;
        case 2: // MESSAGE_DATA
          return MESSAGE_DATA;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.USER_ID_RECEIVE, new org.apache.thrift.meta_data.FieldMetaData("userIdReceive", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32))));
    tmpMap.put(_Fields.MESSAGE_DATA, new org.apache.thrift.meta_data.FieldMetaData("messageData", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TResponseInfo.class, metaDataMap);
  }

  public TResponseInfo() {
  }

  public TResponseInfo(
    List<Integer> userIdReceive,
    ByteBuffer messageData)
  {
    this();
    this.userIdReceive = userIdReceive;
    this.messageData = messageData;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TResponseInfo(TResponseInfo other) {
    if (other.isSetUserIdReceive()) {
      List<Integer> __this__userIdReceive = new ArrayList<Integer>();
      for (Integer other_element : other.userIdReceive) {
        __this__userIdReceive.add(other_element);
      }
      this.userIdReceive = __this__userIdReceive;
    }
    if (other.isSetMessageData()) {
      this.messageData = org.apache.thrift.TBaseHelper.copyBinary(other.messageData);
;
    }
  }

  public TResponseInfo deepCopy() {
    return new TResponseInfo(this);
  }

  @Override
  public void clear() {
    this.userIdReceive = null;
    this.messageData = null;
  }

  public int getUserIdReceiveSize() {
    return (this.userIdReceive == null) ? 0 : this.userIdReceive.size();
  }

  public java.util.Iterator<Integer> getUserIdReceiveIterator() {
    return (this.userIdReceive == null) ? null : this.userIdReceive.iterator();
  }

  public void addToUserIdReceive(int elem) {
    if (this.userIdReceive == null) {
      this.userIdReceive = new ArrayList<Integer>();
    }
    this.userIdReceive.add(elem);
  }

  public List<Integer> getUserIdReceive() {
    return this.userIdReceive;
  }

  public TResponseInfo setUserIdReceive(List<Integer> userIdReceive) {
    this.userIdReceive = userIdReceive;
    return this;
  }

  public void unsetUserIdReceive() {
    this.userIdReceive = null;
  }

  /** Returns true if field userIdReceive is set (has been assigned a value) and false otherwise */
  public boolean isSetUserIdReceive() {
    return this.userIdReceive != null;
  }

  public void setUserIdReceiveIsSet(boolean value) {
    if (!value) {
      this.userIdReceive = null;
    }
  }

  public byte[] getMessageData() {
    setMessageData(org.apache.thrift.TBaseHelper.rightSize(messageData));
    return messageData == null ? null : messageData.array();
  }

  public ByteBuffer bufferForMessageData() {
    return messageData;
  }

  public TResponseInfo setMessageData(byte[] messageData) {
    setMessageData(messageData == null ? (ByteBuffer)null : ByteBuffer.wrap(messageData));
    return this;
  }

  public TResponseInfo setMessageData(ByteBuffer messageData) {
    this.messageData = messageData;
    return this;
  }

  public void unsetMessageData() {
    this.messageData = null;
  }

  /** Returns true if field messageData is set (has been assigned a value) and false otherwise */
  public boolean isSetMessageData() {
    return this.messageData != null;
  }

  public void setMessageDataIsSet(boolean value) {
    if (!value) {
      this.messageData = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case USER_ID_RECEIVE:
      if (value == null) {
        unsetUserIdReceive();
      } else {
        setUserIdReceive((List<Integer>)value);
      }
      break;

    case MESSAGE_DATA:
      if (value == null) {
        unsetMessageData();
      } else {
        setMessageData((ByteBuffer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case USER_ID_RECEIVE:
      return getUserIdReceive();

    case MESSAGE_DATA:
      return getMessageData();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case USER_ID_RECEIVE:
      return isSetUserIdReceive();
    case MESSAGE_DATA:
      return isSetMessageData();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TResponseInfo)
      return this.equals((TResponseInfo)that);
    return false;
  }

  public boolean equals(TResponseInfo that) {
    if (that == null)
      return false;

    boolean this_present_userIdReceive = true && this.isSetUserIdReceive();
    boolean that_present_userIdReceive = true && that.isSetUserIdReceive();
    if (this_present_userIdReceive || that_present_userIdReceive) {
      if (!(this_present_userIdReceive && that_present_userIdReceive))
        return false;
      if (!this.userIdReceive.equals(that.userIdReceive))
        return false;
    }

    boolean this_present_messageData = true && this.isSetMessageData();
    boolean that_present_messageData = true && that.isSetMessageData();
    if (this_present_messageData || that_present_messageData) {
      if (!(this_present_messageData && that_present_messageData))
        return false;
      if (!this.messageData.equals(that.messageData))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(TResponseInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    TResponseInfo typedOther = (TResponseInfo)other;

    lastComparison = Boolean.valueOf(isSetUserIdReceive()).compareTo(typedOther.isSetUserIdReceive());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUserIdReceive()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.userIdReceive, typedOther.userIdReceive);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetMessageData()).compareTo(typedOther.isSetMessageData());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMessageData()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.messageData, typedOther.messageData);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TResponseInfo(");
    boolean first = true;

    sb.append("userIdReceive:");
    if (this.userIdReceive == null) {
      sb.append("null");
    } else {
      sb.append(this.userIdReceive);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("messageData:");
    if (this.messageData == null) {
      sb.append("null");
    } else {
      org.apache.thrift.TBaseHelper.toString(this.messageData, sb);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TResponseInfoStandardSchemeFactory implements SchemeFactory {
    public TResponseInfoStandardScheme getScheme() {
      return new TResponseInfoStandardScheme();
    }
  }

  private static class TResponseInfoStandardScheme extends StandardScheme<TResponseInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TResponseInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // USER_ID_RECEIVE
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.userIdReceive = new ArrayList<Integer>(_list0.size);
                for (int _i1 = 0; _i1 < _list0.size; ++_i1)
                {
                  int _elem2; // required
                  _elem2 = iprot.readI32();
                  struct.userIdReceive.add(_elem2);
                }
                iprot.readListEnd();
              }
              struct.setUserIdReceiveIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // MESSAGE_DATA
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.messageData = iprot.readBinary();
              struct.setMessageDataIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TResponseInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.userIdReceive != null) {
        oprot.writeFieldBegin(USER_ID_RECEIVE_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I32, struct.userIdReceive.size()));
          for (int _iter3 : struct.userIdReceive)
          {
            oprot.writeI32(_iter3);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.messageData != null) {
        oprot.writeFieldBegin(MESSAGE_DATA_FIELD_DESC);
        oprot.writeBinary(struct.messageData);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TResponseInfoTupleSchemeFactory implements SchemeFactory {
    public TResponseInfoTupleScheme getScheme() {
      return new TResponseInfoTupleScheme();
    }
  }

  private static class TResponseInfoTupleScheme extends TupleScheme<TResponseInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TResponseInfo struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetUserIdReceive()) {
        optionals.set(0);
      }
      if (struct.isSetMessageData()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetUserIdReceive()) {
        {
          oprot.writeI32(struct.userIdReceive.size());
          for (int _iter4 : struct.userIdReceive)
          {
            oprot.writeI32(_iter4);
          }
        }
      }
      if (struct.isSetMessageData()) {
        oprot.writeBinary(struct.messageData);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TResponseInfo struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list5 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I32, iprot.readI32());
          struct.userIdReceive = new ArrayList<Integer>(_list5.size);
          for (int _i6 = 0; _i6 < _list5.size; ++_i6)
          {
            int _elem7; // required
            _elem7 = iprot.readI32();
            struct.userIdReceive.add(_elem7);
          }
        }
        struct.setUserIdReceiveIsSet(true);
      }
      if (incoming.get(1)) {
        struct.messageData = iprot.readBinary();
        struct.setMessageDataIsSet(true);
      }
    }
  }

}

